name: conda envs build and test
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
    

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - name: Install dependencies
              run: |
                 C:\Miniconda\condabin\conda.bat env update --file environment.yml --name base
                 C:\Miniconda\condabin\conda.bat init powershell
            - name: Install local packages
              run: |
                  pip install -e.
            - name: Train
              run : |
                  C:\Miniconda\condabin\conda.bat activate base
                  python scripts/train_enc.py -e 1
                  python scripts/trian_dec.py -e 1
                  
          



    
